-- 공간을 둘 이상 등록한 사람 = '헤비 유저'
-- 헤비 유저가 등록한 공간의 정보를 아이디 순으로 조회
SELECT DISTINCT A.ID, A.NAME, A.HOST_ID FROM PLACES A
LEFT OUTER JOIN PLACES B
ON A.HOST_ID = B.HOST_ID
WHERE A.NAME != B.NAME
ORDER BY A.ID;

SELECT * FROM PLACES A
WHERE EXISTS (
    SELECT 1 FROM PLACES B
    WHERE A.HOST_ID = B.HOST_ID
    GROUP BY HOST_ID
    HAVING COUNT(ID) >= 2
)
ORDER BY ID;