-- 우유와 요거트를 동시에 구입한 장바구니의 아이디 조회
-- 장바구니의 아이디 순으로 조회

-- EXISTS 활용
SELECT DISTINCT CART_ID FROM CART_PRODUCTS A
WHERE NAME='Milk'
AND EXISTS (
    SELECT 1 FROM CART_PRODUCTS B
    WHERE A.CART_ID=B.CART_ID AND NAME='Yogurt')
ORDER BY CART_ID;


-- IN &  서브쿼리 활용
SELECT DISTINCT CART_ID FROM CART_PRODUCTS
WHERE NAME = 'Milk'
AND CART_ID IN (SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME='Yogurt');