-- 9시부터 19시, 각 시간대별로 입양 몇 건 발생했는지 조회
-- 시간대 순으로 정렬
SELECT Substring(DATETIME,12,2) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY Substring(DATETIME,12,2)
HAVING HOUR >= '09' AND HOUR <= '19'
ORDER BY SUBSTRING(DATETIME,12,2)